shopt -s nullglob
files=(App/Resources/Fonts/*)
infoplist="App/Generated/Autogenerated/UIAppFonts.generated.plist"
echo $files

/usr/libexec/PlistBuddy -c 'Delete UIAppFonts' "$infoplist"
/usr/libexec/PlistBuddy -c 'Add UIAppFonts array' "$infoplist"

for ((i=0; i<"${#files[@]}"; i++)); do
    #do something to each element of array
    entry=$(basename "${files[$i]}")
    /usr/libexec/PlistBuddy -c "Add UIAppFonts:${index} string ${entry}" "$infoplist"
done