name: banks-client
settings:
  IPHONEOS_DEPLOYMENT_TARGET: 13.0
  SWIFT_VERSION: 5.0

options:
  createIntermediateGroups: true

configs:
  Dev Debug: debug
  Preprod Debug: debug
  Production Debug: debug
  Dev Release: release
  Preprod Release: release
  Production Release: release

targets:
  Banks:
    platform: iOS
    type: application

    scheme:
      configVariants:
        - Dev
        - Preprod
        - Production

    configVariants:
      - Dev
      - Preprod
      - Production

    configFiles:
      Dev Debug: ../App/Configs/dev.xcconfig
      Dev Release: ../App/Configs/dev.xcconfig

      Production Debug: ../App/Configs/production.xcconfig
      Production Release: ../App/Configs/production.xcconfig

      Preprod Debug: ../App/Configs/preprod.xcconfig
      Preprod Release: ../App/Configs/preprod.xcconfig

    info:
      path: ../App/Project/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        ITSAppUsesNonExemptEncryption: NO
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        CFBundleShortVersionString: $(APP_VERSION)
        APP_ENVIRONMENT: $(APP_ENVIRONMENT)
        API_HOST: $(API_HOST)
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: NO
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
                UISceneConfigurationName: Default Configuration

    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      configs:
        Dev:
          PRODUCT_BUNDLE_IDENTIFIER: com.nivanchikov.banks.dev
        Preprod:
          PRODUCT_BUNDLE_IDENTIFIER: com.nivanchikov.banks.preprod
        Production:
          PRODUCT_BUNDLE_IDENTIFIER: com.nivanchikov.banks

    sources: 
      - ../App/Sources
      - ../App/Generated

      - path: ../App/Generated/Autogenerated/R.generated.swift
        optional: true

      - path: ../App/Resources


    preBuildScripts:
      # - path: ../Scripts/fonts.sh
      #   name: Fonts

      # - path: ../Scripts/sourcery.sh
      #   name: Sourcery

      - path: ../Scripts/r-swift.sh
        name: R.swift
        inputFiles:
          - $TEMP_DIR/rswift-lastrun
        outputFiles:
          - $SRCROOT/App/Generated/Autogenerated/R.generated.swift

      - path: ../Scripts/barty-crouch.sh
        name: BartyCrouch

    postCompileScripts:
      - path: ../Scripts/swiftlint.sh
        name: Swiftlint

      # - path: ../Scripts/embed_firebase.sh
      #   name: Embed Firebase plist

    # postBuildScripts:
    #   - path: ../Scripts/fabric.sh
    #     name: Fabric
    #     inputFiles:
    #       - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
    #       - $(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)



